{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3manager.fullname" . }}
  labels:
    {{- include "s3manager.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data | nindent 2}}
{{- end }}